# Generated by Django 4.0.4 on 2022-05-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='очки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=models.TextField(verbose_name='ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ид вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='текст вопроса'),
        ),
    ]
